CREATE TABLE IF NOT EXISTS exercises (id serial PRIMARY KEY, name text NOT NULL UNIQUE, category text NOT NULL DEFAULT 'strength', unit text NOT NULL DEFAULT 'lb', notes text);
CREATE TABLE IF NOT EXISTS workout_sessions (id serial PRIMARY KEY, performed_on date NOT NULL UNIQUE, session_type text NOT NULL DEFAULT 'upper-skills', completed boolean NOT NULL DEFAULT false, energy integer, protein_target_met boolean, hydration_target_met boolean, notes text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS exercise_sets (id serial PRIMARY KEY, workout_session_id integer NOT NULL REFERENCES workout_sessions(id) ON DELETE CASCADE, exercise_id integer NOT NULL REFERENCES exercises(id), set_number integer NOT NULL, reps integer, weight text, rpe numeric(3,1), variation text, notes text);
CREATE UNIQUE INDEX IF NOT EXISTS exercise_sets_session_exercise_set_idx ON exercise_sets(workout_session_id, exercise_id, set_number);
CREATE TABLE IF NOT EXISTS cardio_sessions (id serial PRIMARY KEY, performed_on date NOT NULL, activity text NOT NULL, duration_minutes integer, run_minutes integer, distance_miles numeric(6,2), pace_seconds_per_mile integer, pain_during integer, pain_after integer, next_day_pain integer, notes text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS mobility_sessions (id serial PRIMARY KEY, performed_on date NOT NULL, hip boolean NOT NULL DEFAULT false, ankle_calf boolean NOT NULL DEFAULT false, neck_upper_back boolean NOT NULL DEFAULT false, split_practice boolean NOT NULL DEFAULT false, minutes integer, stiffness integer, notes text);
CREATE TABLE IF NOT EXISTS daily_checkins (id serial PRIMARY KEY, checkin_date date NOT NULL UNIQUE, protein_target_met boolean, calorie_range_met boolean, hydration_target_met boolean, energy integer, sleep_hours numeric(4,1), notes text);
CREATE TABLE IF NOT EXISTS progress_metrics (id serial PRIMARY KEY, measured_on date NOT NULL, weight_lb numeric(5,1), waist_in numeric(5,2), pushups integer, pullup_assistance_lb numeric(6,1), pullups integer, mile_seconds integer, split_distance_in numeric(5,2), notes text);
CREATE TABLE IF NOT EXISTS training_blocks (id serial PRIMARY KEY, name text NOT NULL, starts_on date NOT NULL, ends_on date NOT NULL, focus text NOT NULL, notes text);
