'use client';

import { useEffect, useMemo, useState } from 'react';
import { blockForDate, localDateKey, planForDate, PROGRAM_START, runStages, trainingBlocks, weeklyPlans } from '@/lib/program';

type SetLog={weight:string;reps:string};
type Exercise={name:string;target:string;note?:string;sets:SetLog[]};
type DayLog={done:boolean;energy:number;protein:boolean;water:boolean;sessionType:string;exercises:Exercise[]};
type PreviousRow={date:string;exerciseName:string;setNumber:number;weight:string|null;reps:number|null};
type TrackerData={checkin:any;cardio:any[];mobility:any[];progress:any[]};

function buildExercises():Exercise[]{const p=planForDate();return (p.exercises||[]).map(ex=>({name:ex.name,target:ex.target,note:ex.note,sets:Array.from({length:ex.sets},()=>({weight:ex.defaultWeight||'',reps:''}))}))}
function freshLog():DayLog{const p=planForDate();return{done:false,energy:3,protein:false,water:false,sessionType:p.key,exercises:buildExercises()}}
function suggestion(ex:Exercise,rows:PreviousRow[]){const dates=Array.from(new Set(rows.filter(r=>r.exerciseName===ex.name).map(r=>r.date)));if(!dates.length)return 'First logged session — establish a clean baseline.';const last=rows.filter(r=>r.exerciseName===ex.name&&r.date===dates[0]);const reps:number[]=last.map(r=>r.reps??0);const weight=last[0]?.weight||'same load';const total=reps.reduce((a,b)=>a+b,0);if(ex.name==='Assisted Pull-ups')return `Last: ${weight} assist · ${reps.join('/')} reps. Add clean reps; reduce assistance only after the top of the range.`;if(ex.name==='Push-up Progression')return `Last: ${reps.join('/')} reps. Beat ${total} clean total reps, then lower the incline.`;if(ex.name==='Bench Press')return `Last: ${weight} · ${reps.join('/')} reps. Add clean reps before load.`;if(ex.name==='21s')return `Last: ${weight}. Progress 5-5-5 → 6-6-6 → 7-7-7, then add load.`;return `Last: ${weight} · ${reps.join('/')} reps. Add reps within the target range before load.`}

export default function Home(){
  const todayPlan=useMemo(()=>planForDate(),[]);const todayKey=useMemo(()=>localDateKey(),[]);const block=useMemo(()=>blockForDate(todayKey),[todayKey]);
  const projectDay=useMemo(()=>{const start=new Date(`${PROGRAM_START}T00:00:00`);const now=new Date();const diff=Math.floor((new Date(now.getFullYear(),now.getMonth(),now.getDate()).getTime()-start.getTime())/86400000);return Math.max(1,diff+1)},[]);
  const[tab,setTab]=useState<'today'|'plan'|'track'|'progress'>('today');const[log,setLog]=useState<DayLog>(freshLog());const[previous,setPrevious]=useState<PreviousRow[]>([]);const[saving,setSaving]=useState(false);const[loaded,setLoaded]=useState(false);const[dbError,setDbError]=useState<string|null>(null);const[saved,setSaved]=useState(false);const[tracker,setTracker]=useState<TrackerData>({checkin:null,cardio:[],mobility:[],progress:[]});
  const[cardio,setCardio]=useState({activity:'Run / walk',durationMinutes:'',distanceMiles:'',painDuring:'0',painAfter:'0',nextDayPain:'0',notes:''});
  const[mobility,setMobility]=useState({hip:false,ankleCalf:false,neckUpperBack:false,splitPractice:false,minutes:'10',stiffness:'',notes:''});
  const[progress,setProgress]=useState({weightLb:'',waistIn:'',pushups:'',pullupAssistanceLb:'',pullups:'',mileSeconds:'',splitDistanceIn:'',notes:''});
  const[checkin,setCheckin]=useState({calories:false,protein:false,hydration:false,notes:''});
  const[notice,setNotice]=useState<string|null>(null);

  useEffect(()=>{Promise.all([
    fetch('/api/workouts/today').then(async r=>{if(!r.ok){const j=await r.json().catch(()=>null);throw new Error(j?.error||`Workout load failed (${r.status})`)}return r.json()}),
    fetch('/api/tracker').then(async r=>{if(!r.ok){const j=await r.json().catch(()=>null);throw new Error(j?.error||`Tracker load failed (${r.status})`)}return r.json()})
  ]).then(([workoutData,trackerData])=>{setPrevious(workoutData.previous||[]);if(workoutData.log){const next=freshLog();next.done=workoutData.log.done;next.energy=workoutData.log.energy;next.protein=workoutData.log.protein;next.water=workoutData.log.water;for(const row of workoutData.log.rows){const ex=next.exercises.find(e=>e.name===row.exerciseName);if(ex&&ex.sets[row.setNumber-1])ex.sets[row.setNumber-1]={weight:row.weight||'',reps:row.reps?.toString()||''}}setLog(next);setSaved(next.done)}setTracker(trackerData);if(trackerData.checkin)setCheckin({calories:!!trackerData.checkin.calorieRangeMet,protein:!!trackerData.checkin.proteinTargetMet,hydration:!!trackerData.checkin.hydrationTargetMet,notes:trackerData.checkin.notes||''});setDbError(null);setLoaded(true)}).catch(e=>{setDbError(e instanceof Error?e.message:'Unable to sync with database');setLoaded(true)});},[]);

  async function saveWorkout(next=log){setSaving(true);setDbError(null);try{const r=await fetch('/api/workouts/today',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});if(!r.ok){const j=await r.json().catch(()=>null);throw new Error(j?.error||`Save failed (${r.status})`)}setSaved(true);setNotice('Workout saved')}catch(e){setSaved(false);setDbError(e instanceof Error?e.message:'Unable to save workout')}finally{setSaving(false)}}
  async function saveTracker(payload:any,message:string){setNotice(null);setDbError(null);const r=await fetch('/api/tracker',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const j=await r.json().catch(()=>null);setDbError(j?.error||`Save failed (${r.status})`);return}setNotice(message);const fresh=await fetch('/api/tracker').then(x=>x.json());setTracker(fresh)}
  function editSet(ei:number,si:number,field:keyof SetLog,value:string){setSaved(false);setLog(p=>{const n=structuredClone(p);n.exercises[ei].sets[si][field]=value;return n})}

  return <main className="shell">
    <header><div><p className="eyebrow">6 MONTH PROJECT</p><h1>Strong, capable, consistent.</h1>{block&&<p className="subtle">{block.name} · {block.focus}</p>}</div><div className="streak">Day {projectDay}</div></header>
    {dbError&&<section className="card errorCard"><p className="eyebrow">DATABASE SYNC ERROR</p><p>{dbError}</p></section>}{notice&&<section className="card successCard"><b>{notice}</b></section>}

    {tab==='today'&&<>
      <section className="hero card"><p className="eyebrow">TODAY · {todayPlan.label.toUpperCase()}</p><h2>{todayPlan.description}</h2><p>{todayPlan.duration}{todayPlan.cardio?` · ${todayPlan.cardio}`:''}</p><div className="checks"><button className={log.protein?'active':''} onClick={()=>{setSaved(false);setLog({...log,protein:!log.protein})}}>✓ Protein</button><button className={log.water?'active':''} onClick={()=>{setSaved(false);setLog({...log,water:!log.water})}}>✓ Hydration</button></div></section>
      {todayPlan.exercises&&<><div className="sectionTitle"><h2>Workout</h2><span>{loaded?todayPlan.duration:'Loading…'}</span></div>{log.exercises.map((ex,ei)=><section className="card exercise" key={ex.name}><div className="exerciseHead"><div><h3>{ex.name}</h3><p>{ex.target}</p></div><span>{ei+1}</span></div><p className="note"><b>Next target:</b> {suggestion(ex,previous)}</p>{ex.note&&<p className="subtle">{ex.note}</p>}<div className="setHeader"><span>SET</span><span>WEIGHT / ASSIST</span><span>REPS</span></div>{ex.sets.map((s,si)=><div className="setRow" key={si}><b>{si+1}</b><input value={s.weight} placeholder="—" onChange={e=>editSet(ei,si,'weight',e.target.value)}/><input inputMode="numeric" value={s.reps} placeholder="—" onChange={e=>editSet(ei,si,'reps',e.target.value)}/></div>)}</section>)}</>}
      {todayPlan.mobility&&<section className="card"><p className="eyebrow">MOBILITY</p><h3>Short, useful, repeatable.</h3><div className="chips">{todayPlan.mobility.map(x=><span key={x}>{x}</span>)}</div></section>}
      {todayPlan.exercises&&<><section className="card energy"><h3>How did today feel?</h3><div>{[1,2,3,4,5].map(n=><button key={n} className={log.energy===n?'active':''} onClick={()=>{setSaved(false);setLog({...log,energy:n})}}>{n}</button>)}</div><p>1 = wrecked · 5 = could do more</p></section><button className="finish" disabled={saving} onClick={()=>{const n={...log,done:true,sessionType:todayPlan.key};setLog(n);saveWorkout(n)}}>{saving?'Saving…':saved?'✓ Saved to Postgres':'Finish & save workout'}</button></>}
    </>}

    {tab==='plan'&&<>
      <section className="card plan"><p className="eyebrow">DEFAULT WEEK</p><h2>Three hard days. No punishment workouts.</h2>{[1,2,3,4,5,6,0].map(d=><p key={d}><b>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'][d]}</b> · {weeklyPlans[d].label} — {weeklyPlans[d].description}</p>)}</section>
      <section className="card"><p className="eyebrow">RUNNING PROGRESSION</p><h3>Build below the knee-pain threshold.</h3>{runStages.map((s,i)=><p key={s}><b>{i+1}.</b> {s}</p>)}<p className="note">Progress only if the knee does not significantly flare during the session or the next day. Easy distance comes before speed.</p></section>
      <section className="card"><p className="eyebrow">TRAINING BLOCKS</p>{trainingBlocks.map(b=><div className="blockRow" key={b.name}><b>{b.name}</b><span>{b.start} → {b.end}</span><p>{b.focus}</p></div>)}</section>
    </>}

    {tab==='track'&&<>
      <section className="card"><p className="eyebrow">DAILY CHECK-IN</p><h2>Enough structure, not food-accounting hell.</h2><div className="checks gridChecks"><button className={checkin.protein?'active':''} onClick={()=>setCheckin({...checkin,protein:!checkin.protein})}>Protein ~100g</button><button className={checkin.calories?'active':''} onClick={()=>setCheckin({...checkin,calories:!checkin.calories})}>~1,600–1,700</button><button className={checkin.hydration?'active':''} onClick={()=>setCheckin({...checkin,hydration:!checkin.hydration})}>Hydration</button></div><textarea placeholder="Optional note" value={checkin.notes} onChange={e=>setCheckin({...checkin,notes:e.target.value})}/><button className="secondary" onClick={()=>saveTracker({type:'checkin',...checkin},'Daily check-in saved')}>Save check-in</button></section>
      <section className="card"><p className="eyebrow">RUN + KNEE</p><h2>Log what the knee actually does.</h2><div className="formGrid"><label>Activity<input value={cardio.activity} onChange={e=>setCardio({...cardio,activity:e.target.value})}/></label><label>Minutes<input inputMode="numeric" value={cardio.durationMinutes} onChange={e=>setCardio({...cardio,durationMinutes:e.target.value})}/></label><label>Miles<input inputMode="decimal" value={cardio.distanceMiles} onChange={e=>setCardio({...cardio,distanceMiles:e.target.value})}/></label><label>Pain during 0–10<input inputMode="numeric" value={cardio.painDuring} onChange={e=>setCardio({...cardio,painDuring:e.target.value})}/></label><label>Pain after 0–10<input inputMode="numeric" value={cardio.painAfter} onChange={e=>setCardio({...cardio,painAfter:e.target.value})}/></label><label>Next-day pain 0–10<input inputMode="numeric" value={cardio.nextDayPain} onChange={e=>setCardio({...cardio,nextDayPain:e.target.value})}/></label></div><textarea placeholder="Trigger / notes" value={cardio.notes} onChange={e=>setCardio({...cardio,notes:e.target.value})}/><button className="secondary" onClick={()=>saveTracker({type:'cardio',...cardio},'Cardio + knee log saved')}>Save run/cardio</button></section>
      <section className="card"><p className="eyebrow">MOBILITY</p><div className="checks gridChecks"><button className={mobility.hip?'active':''} onClick={()=>setMobility({...mobility,hip:!mobility.hip})}>Hips</button><button className={mobility.ankleCalf?'active':''} onClick={()=>setMobility({...mobility,ankleCalf:!mobility.ankleCalf})}>Ankle / calf</button><button className={mobility.neckUpperBack?'active':''} onClick={()=>setMobility({...mobility,neckUpperBack:!mobility.neckUpperBack})}>Neck / upper back</button><button className={mobility.splitPractice?'active':''} onClick={()=>setMobility({...mobility,splitPractice:!mobility.splitPractice})}>Split</button></div><div className="formGrid"><label>Minutes<input inputMode="numeric" value={mobility.minutes} onChange={e=>setMobility({...mobility,minutes:e.target.value})}/></label><label>Stiffness 0–10<input inputMode="numeric" value={mobility.stiffness} onChange={e=>setMobility({...mobility,stiffness:e.target.value})}/></label></div><button className="secondary" onClick={()=>saveTracker({type:'mobility',...mobility},'Mobility saved')}>Save mobility</button></section>
    </>}

    {tab==='progress'&&<>
      <section className="card"><p className="eyebrow">THE SCOREBOARD</p><h2>Performance first.</h2><div className="metrics"><div><strong>Push-ups</strong><span>0 → 10 floor reps</span></div><div><strong>Pull-up</strong><span>Assisted → 1 unassisted</span></div><div><strong>Running</strong><span>Easy mile → 8:00 mile</span></div><div><strong>Mobility</strong><span>Split + hip/knee/neck control</span></div></div></section>
      <section className="card"><p className="eyebrow">CHECK-IN</p><div className="formGrid"><label>Weight (optional)<input inputMode="decimal" value={progress.weightLb} onChange={e=>setProgress({...progress,weightLb:e.target.value})}/></label><label>Waist (optional)<input inputMode="decimal" value={progress.waistIn} onChange={e=>setProgress({...progress,waistIn:e.target.value})}/></label><label>Floor push-ups<input inputMode="numeric" value={progress.pushups} onChange={e=>setProgress({...progress,pushups:e.target.value})}/></label><label>Pull-up assistance lb<input inputMode="decimal" value={progress.pullupAssistanceLb} onChange={e=>setProgress({...progress,pullupAssistanceLb:e.target.value})}/></label><label>Unassisted pull-ups<input inputMode="numeric" value={progress.pullups} onChange={e=>setProgress({...progress,pullups:e.target.value})}/></label><label>Mile seconds<input inputMode="numeric" value={progress.mileSeconds} onChange={e=>setProgress({...progress,mileSeconds:e.target.value})}/></label><label>Split distance in<input inputMode="decimal" value={progress.splitDistanceIn} onChange={e=>setProgress({...progress,splitDistanceIn:e.target.value})}/></label></div><textarea placeholder="Optional progress note" value={progress.notes} onChange={e=>setProgress({...progress,notes:e.target.value})}/><button className="secondary" onClick={()=>saveTracker({type:'progress',...progress},'Progress check-in saved')}>Save progress</button></section>
      <section className="card"><p className="eyebrow">RECENT HISTORY</p>{tracker.progress.length===0?<p className="subtle">No progress check-ins yet.</p>:tracker.progress.map((p:any)=><div className="historyRow" key={p.id}><b>{p.measuredOn}</b><span>Push-ups {p.pushups??'—'} · Pull-up assist {p.pullupAssistanceLb??'—'} · Mile {p.mileSeconds??'—'}s</span></div>)}</section>
    </>}

    <nav><button className={tab==='today'?'active':''} onClick={()=>setTab('today')}>Today</button><button className={tab==='plan'?'active':''} onClick={()=>setTab('plan')}>Plan</button><button className={tab==='track'?'active':''} onClick={()=>setTab('track')}>Track</button><button className={tab==='progress'?'active':''} onClick={()=>setTab('progress')}>Progress</button></nav>
  </main>
}
