'use client';

import Link from 'next/link';
import { useEffect, useMemo, useRef, useState } from 'react';
import { blockForDate, localDateKey, planForDate, PROGRAM_START } from '@/lib/program';
import { exerciseReferenceHref } from '@/lib/exercise-reference';
import TodayPractice from './components/TodayPractice';

type SetLog={weight:string;reps:string;leftReps:string;rightReps:string};
type Exercise={name:string;target:string;note?:string;sets:SetLog[];plannedSets:number;unilateral?:boolean};
type DayLog={done:boolean;energy:number;protein:boolean;water:boolean;limited:boolean;limitationNotes:string;sessionType:string;exercises:Exercise[]};
type PreviousRow={date:string;exerciseName:string;setNumber:number;weight:string|null;reps:number|null};
type ProgressRow={measuredOn:string};

const emptySet=(weight=''):SetLog=>({weight,reps:'',leftReps:'',rightReps:''});
function buildExercises():Exercise[]{const p=planForDate();return (p.exercises||[]).map(ex=>({name:ex.name,target:ex.target,note:ex.note,plannedSets:ex.sets,unilateral:ex.unilateral,sets:Array.from({length:ex.sets},()=>emptySet(ex.defaultWeight||''))}))}
function freshLog():DayLog{const p=planForDate();return{done:false,energy:3,protein:false,water:false,limited:false,limitationNotes:'',sessionType:p.key,exercises:buildExercises()}}
function suggestion(ex:Exercise,rows:PreviousRow[]){const dates=Array.from(new Set(rows.filter(r=>r.exerciseName===ex.name).map(r=>r.date)));if(!dates.length)return 'First logged session — establish a clean baseline.';const last=rows.filter(r=>r.exerciseName===ex.name&&r.date===dates[0]);const reps:number[]=last.map(r=>r.reps??0);const weight=last[0]?.weight||'same load';const total=reps.reduce((a,b)=>a+b,0);if(ex.name==='Assisted Pull-ups')return `Last: ${weight} assist · ${reps.join('/')} reps. Add clean reps; reduce assistance only after the top of the range.`;if(ex.name==='Push-up Progression')return `Last: ${reps.join('/')} reps. Beat ${total} clean total reps, then lower the incline.`;if(ex.name==='Bench Press')return `Last: ${weight} · ${reps.join('/')} reps. Add clean reps before load.`;if(ex.name==='21s')return `Last: ${weight}. Progress 5-5-5 → 6-6-6 → 7-7-7, then add load.`;return `Last: ${weight} · ${reps.join('/')} reps. Add reps within the target range before load.`}

function foodPlanForDate(d=new Date()){
  const key=localDateKey(d);const day=d.getDay();const sepWfh=key>='2026-09-01'&&key<='2026-09-04';const office=[1,2,4,5].includes(day)&&!sepWfh;
  return {
    breakfast:'Protein drink + fruit + bagel or toast',
    lunch:office?'Forkable: choose a meal with a clear protein + carb + vegetable. No optimizing beyond that.':'Choose one: Greek yogurt + fruit + granola + protein drink; microwave rice + fully cooked chicken + bagged salad; or order a chicken, steak, or tofu bowl.',
    dinners:['Chicken + rice + veg','Mediterranean chicken + rice/pita + salad + hummus','Sushi + edamame','Indian chicken + rice + veg','Steak + potato/rice + veg','Salmon + rice + veg','Tofu + rice + veg'],
    emergency:'Too tired to decide: protein drink + fruit now, then pick one dinner default. Taco Bell is allowed on purpose — it is not a failed day.',
    note:'Aim roughly for 1,600–1,700 calories on average and ~100g protein. You do not need to log every meal here.'
  };
}

export default function Home(){
  const todayPlan=useMemo(()=>planForDate(),[]);const todayKey=useMemo(()=>localDateKey(),[]);const block=useMemo(()=>blockForDate(todayKey),[todayKey]);const food=useMemo(()=>foodPlanForDate(),[]);
  const projectDay=useMemo(()=>{const [sy,sm,sd]=PROGRAM_START.split('-').map(Number);const now=new Date();const diff=Math.floor((Date.UTC(now.getFullYear(),now.getMonth(),now.getDate())-Date.UTC(sy,sm-1,sd))/86400000);return Math.max(1,diff+1)},[]);
  const[log,setLog]=useState<DayLog>(freshLog());const[previous,setPrevious]=useState<PreviousRow[]>([]);const[saving,setSaving]=useState(false);const[autoSaveState,setAutoSaveState]=useState<'idle'|'saving'|'saved'>('idle');const[loaded,setLoaded]=useState(false);const[dbError,setDbError]=useState<string|null>(null);const[saved,setSaved]=useState(false);const[notice,setNotice]=useState<string|null>(null);const[progressRows,setProgressRows]=useState<ProgressRow[]>([]);const[menuOpen,setMenuOpen]=useState(false);const lastPersisted=useRef('');
  const[cardio,setCardio]=useState({activity:'Run / walk',durationMinutes:'',distanceMiles:'',painDuring:'0',painAfter:'0',nextDayPain:'0',notes:''});
  const[progress,setProgress]=useState({weightLb:'',waistIn:'',pushups:'',pullupAssistanceLb:'',pullups:'',mileSeconds:'',splitDistanceIn:'',notes:''});

  useEffect(()=>{document.body.classList.toggle('menuOpen',menuOpen);return()=>document.body.classList.remove('menuOpen')},[menuOpen]);
  useEffect(()=>{Promise.all([
    fetch(`/api/workouts/today?date=${todayKey}`).then(async r=>{if(!r.ok){const j=await r.json().catch(()=>null);throw new Error(j?.error||`Workout load failed (${r.status})`)}return r.json()}),
    fetch(`/api/tracker?date=${todayKey}`).then(async r=>{if(!r.ok){const j=await r.json().catch(()=>null);throw new Error(j?.error||`Tracker load failed (${r.status})`)}return r.json()})
  ]).then(([workoutData,trackerData])=>{setPrevious(workoutData.previous||[]);setProgressRows(trackerData.progress||[]);if(workoutData.log){const next=freshLog();next.done=workoutData.log.done;next.energy=workoutData.log.energy;next.limited=!!workoutData.log.limited;next.limitationNotes=workoutData.log.limitationNotes||'';for(const row of workoutData.log.rows){const ex=next.exercises.find(e=>e.name===row.exerciseName);if(ex){while(ex.sets.length<row.setNumber)ex.sets.push(emptySet());ex.sets[row.setNumber-1]={weight:row.weight||'',reps:row.reps?.toString()||'',leftReps:row.leftReps?.toString()||'',rightReps:row.rightReps?.toString()||''}}}lastPersisted.current=JSON.stringify({...next,date:todayKey});setLog(next);setSaved(next.done)}else{lastPersisted.current=JSON.stringify({...freshLog(),date:todayKey})}setDbError(null);setLoaded(true)}).catch(e=>{setDbError(e instanceof Error?e.message:'Unable to sync with database');setLoaded(true)});},[todayKey]);

  useEffect(()=>{if(!loaded||!todayPlan.exercises)return;const serialized=JSON.stringify({...log,date:todayKey});if(serialized===lastPersisted.current)return;setAutoSaveState('idle');const timer=window.setTimeout(async()=>{setAutoSaveState('saving');try{const r=await fetch('/api/workouts/today',{method:'PUT',headers:{'Content-Type':'application/json'},body:serialized});if(!r.ok){const j=await r.json().catch(()=>null);throw new Error(j?.error||`Autosave failed (${r.status})`)}lastPersisted.current=serialized;setAutoSaveState('saved');setDbError(null)}catch(e){setAutoSaveState('idle');setDbError(e instanceof Error?e.message:'Unable to autosave workout')}},700);return()=>window.clearTimeout(timer)},[log,loaded,todayPlan.exercises,todayKey]);

  const monthlyCheckinDue=useMemo(()=>{if(!progressRows.length)return true;const last=new Date(`${progressRows[0].measuredOn}T00:00:00`);const today=new Date(`${todayKey}T00:00:00`);return today.getTime()-last.getTime()>=28*86400000},[progressRows,todayKey]);
  const showRunLog=todayPlan.kind==='cardio'||Boolean(todayPlan.cardio);

  async function saveWorkout(next=log){setSaving(true);setDbError(null);const payload={...next,date:todayKey};try{const r=await fetch('/api/workouts/today',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const j=await r.json().catch(()=>null);throw new Error(j?.error||`Save failed (${r.status})`)}lastPersisted.current=JSON.stringify(payload);setSaved(next.done);setAutoSaveState('saved');setNotice(next.done?'Workout saved':'Workout updated')}catch(e){setDbError(e instanceof Error?e.message:'Unable to save workout')}finally{setSaving(false)}}
  async function saveTracker(payload:any,message:string){setNotice(null);setDbError(null);const r=await fetch('/api/tracker',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,date:todayKey})});if(!r.ok){const j=await r.json().catch(()=>null);setDbError(j?.error||`Save failed (${r.status})`);return}setNotice(message);const fresh=await fetch(`/api/tracker?date=${todayKey}`).then(x=>x.json());setProgressRows(fresh.progress||[])}
  function editSet(ei:number,si:number,field:keyof SetLog,value:string){setLog(p=>{const n=structuredClone(p);n.exercises[ei].sets[si][field]=value;return n})}
  function addSet(ei:number){setLog(p=>{const n=structuredClone(p);n.exercises[ei].sets.push(emptySet());return n})}
  function removeExtraSet(ei:number,si:number){setLog(p=>{const n=structuredClone(p);const ex=n.exercises[ei];if(si>=ex.plannedSets)ex.sets.splice(si,1);return n})}

  return <main className="shell">
    <header className="appHeader"><div><p className="eyebrow">SIX MONTH PRACTICE</p><h1>Sadhana</h1><span className="dayPill">Day {projectDay}</span>{block&&<p className="subtle">{block.name} · {block.focus}</p>}</div><button className={`menuButton ${menuOpen?'open':''}`} aria-label={menuOpen?'Close menu':'Open menu'} aria-expanded={menuOpen} onClick={()=>setMenuOpen(v=>!v)}><span/><span/><span/></button></header>

    <div className={`mobileMenu ${menuOpen?'open':''}`} aria-hidden={!menuOpen}>
      <div className="mobileMenuInner"><p className="eyebrow">MENU</p><Link href="/progress" onClick={()=>setMenuOpen(false)}>Progress <span>→</span></Link><Link href="/exercises" onClick={()=>setMenuOpen(false)}>Exercises <span>→</span></Link><Link href="/wearables" onClick={()=>setMenuOpen(false)}>Wearables <span>→</span></Link><Link href="/about" onClick={()=>setMenuOpen(false)}>About <span>→</span></Link></div>
    </div>

    {dbError&&<section className="card errorCard"><p className="eyebrow">DATABASE SYNC ERROR</p><p>{dbError}</p></section>}{notice&&<section className="card successCard"><b>{notice}</b></section>}

    <section className="hero card"><p className="eyebrow">TODAY · {todayPlan.label.toUpperCase()}</p><h2>{todayPlan.description}</h2><p>{todayPlan.duration}{todayPlan.cardio?` · ${todayPlan.cardio}`:''}</p></section>
    <TodayPractice todayKey={todayKey} plan={todayPlan} workoutDone={saved||log.limited}/>

    <div className="sectionTitle"><h2>Food today</h2><span>Decisions already made</span></div>
    <section className="card foodPlan"><div><b>Breakfast</b><p>{food.breakfast}</p></div><div><b>Lunch</b><p>{food.lunch}</p></div><div><b>Dinner</b><p style={{marginBottom:8}}>Pick one default:</p><ul style={{margin:'0 0 2px',paddingLeft:20,lineHeight:1.7,color:'#e8d5d2'}}>{food.dinners.map(option=><li key={option}>{option}</li>)}</ul></div><div className="foodEmergency"><b>If you’re too tired to decide</b><p>{food.emergency}</p></div><p className="note">{food.note}</p></section>

    {todayPlan.exercises&&<><div className="sectionTitle"><h2>Workout</h2><span>{autoSaveState==='saving'?'Saving…':autoSaveState==='saved'?'Saved':loaded?todayPlan.duration:'Loading…'}</span></div>{log.exercises.map((ex,ei)=><section className="card exercise" key={ex.name}><div className="exerciseHead"><div><h3>{ex.name}</h3><p>{ex.target}</p></div><span>{ei+1}</span></div><p className="note"><b>Next target:</b> {suggestion(ex,previous)}</p>{ex.note&&<p className="subtle">{ex.note}</p>}<div className="setHeader" style={ex.unilateral?{gridTemplateColumns:'38px 1fr 128px'}:undefined}><span>SET</span><span>WEIGHT / ASSIST</span><span>{ex.unilateral?'LEFT / RIGHT':'REPS'}</span></div>{ex.sets.map((s,si)=><div className="setRow" style={ex.unilateral?{gridTemplateColumns:'38px 1fr 128px'}:undefined} key={si}><b>{si+1}</b><input value={s.weight} placeholder="—" onChange={e=>editSet(ei,si,'weight',e.target.value)}/><div className={`repCell ${ex.unilateral?'unilateralReps':''}`}>{ex.unilateral?<><input inputMode="numeric" aria-label={`Set ${si+1} left reps`} value={s.leftReps} placeholder="L" onChange={e=>editSet(ei,si,'leftReps',e.target.value)}/><input inputMode="numeric" aria-label={`Set ${si+1} right reps`} value={s.rightReps} placeholder="R" onChange={e=>editSet(ei,si,'rightReps',e.target.value)}/></>:<input inputMode="numeric" value={s.reps} placeholder="—" onChange={e=>editSet(ei,si,'reps',e.target.value)}/>} {si>=ex.plannedSets&&<button className="removeSet" type="button" aria-label={`Remove extra set ${si+1}`} onClick={()=>removeExtraSet(ei,si)}>×</button>}</div></div>)}<button className="addSet" type="button" onClick={()=>addSet(ei)}>+ Add set</button></section>)}</>}
    {todayPlan.mobility&&<section className="card"><p className="eyebrow">MOBILITY</p><h3>Short, useful, repeatable.</h3><div className="chips">{todayPlan.mobility.map(x=><Link key={x} href={exerciseReferenceHref(x)} style={{textDecoration:'none'}}><span>{x} ↗</span></Link>)}</div></section>}
    {todayPlan.exercises&&<><section className="card"><p className="eyebrow">TRAINING CONTEXT</p><button type="button" className={`limitationToggle ${log.limited?'active':''}`} onClick={()=>setLog({...log,limited:!log.limited,limitationNotes:log.limited?'':log.limitationNotes})}>{log.limited?'✓ Something limited today’s training':'Something limited today’s training'}</button>{log.limited&&<textarea placeholder="What happened? e.g. hand cramped during RDLs, gym closed before I finished" value={log.limitationNotes} onChange={e=>setLog({...log,limitationNotes:e.target.value})}/>}<p className="subtle">An adapted or partial session still counts as showing up. This gives the planner context for what should happen next.</p></section><section className="card energy"><h3>How did the workout feel?</h3><div>{[1,2,3,4,5].map(n=><button key={n} className={log.energy===n?'active':''} onClick={()=>setLog({...log,energy:n})}>{n}</button>)}</div><p>1 = could do more · 5 = wrecked</p></section><button className="finish" disabled={saving} onClick={()=>{const n={...log,done:true,sessionType:todayPlan.key};setLog(n);saveWorkout(n)}}>{saving?'Saving…':saved?'✓ Workout saved':'Finish & save workout'}</button></>}

    {showRunLog&&<section className="card contextualLog"><p className="eyebrow">AFTER CARDIO · OPTIONAL QUICK LOG</p><h2>How did the knee respond?</h2><div className="formGrid"><label>Minutes<input inputMode="numeric" value={cardio.durationMinutes} onChange={e=>setCardio({...cardio,durationMinutes:e.target.value})}/></label><label>Miles<input inputMode="decimal" value={cardio.distanceMiles} onChange={e=>setCardio({...cardio,distanceMiles:e.target.value})}/></label><label>Pain during 0–10<input inputMode="numeric" value={cardio.painDuring} onChange={e=>setCardio({...cardio,painDuring:e.target.value})}/></label><label>Pain after 0–10<input inputMode="numeric" value={cardio.painAfter} onChange={e=>setCardio({...cardio,painAfter:e.target.value})}/></label><label>Next-day pain 0–10<input inputMode="numeric" value={cardio.nextDayPain} onChange={e=>setCardio({...cardio,nextDayPain:e.target.value})}/></label></div><textarea placeholder="Optional trigger / note" value={cardio.notes} onChange={e=>setCardio({...cardio,notes:e.target.value})}/><button className="secondary" onClick={()=>saveTracker({type:'cardio',...cardio},'Knee response saved')}>Save knee response</button></section>}

    {monthlyCheckinDue&&<section className="card periodicCheckin"><p className="eyebrow">MONTHLY CHECK-IN</p><h2>This is occasional, not daily.</h2><p className="subtle">A quick snapshot for trend-level decisions. Weight and waist are optional.</p><div className="formGrid"><label>Weight (optional)<input inputMode="decimal" value={progress.weightLb} onChange={e=>setProgress({...progress,weightLb:e.target.value})}/></label><label>Waist (optional)<input inputMode="decimal" value={progress.waistIn} onChange={e=>setProgress({...progress,waistIn:e.target.value})}/></label><label>Floor push-ups<input inputMode="numeric" value={progress.pushups} onChange={e=>setProgress({...progress,pushups:e.target.value})}/></label><label>Pull-up assistance lb<input inputMode="decimal" value={progress.pullupAssistanceLb} onChange={e=>setProgress({...progress,pullupAssistanceLb:e.target.value})}/></label><label>Unassisted pull-ups<input inputMode="numeric" value={progress.pullups} onChange={e=>setProgress({...progress,pullups:e.target.value})}/></label><label>Mile seconds<input inputMode="numeric" value={progress.mileSeconds} onChange={e=>setProgress({...progress,mileSeconds:e.target.value})}/></label><label>Split distance from floor (in)<input inputMode="decimal" value={progress.splitDistanceIn} onChange={e=>setProgress({...progress,splitDistanceIn:e.target.value})}/></label></div><textarea placeholder="Optional note" value={progress.notes} onChange={e=>setProgress({...progress,notes:e.target.value})}/><button className="secondary" onClick={()=>saveTracker({type:'progress',...progress},'Monthly check-in saved')}>Save monthly check-in</button></section>}

    <nav><Link className="active" href="/">Today</Link><Link href="/plan">Plan</Link></nav>
  </main>
}
