'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { planForDate } from '@/lib/program';

type SetLog={weight:string;reps:string;leftReps:string;rightReps:string};
type ExerciseLog={name:string;plannedSets:number;unilateral?:boolean;sets:SetLog[]};
type WorkoutLog={done:boolean;energy:number;protein:boolean;water:boolean;limited:boolean;limitationNotes:string;sessionType:string;exercises:ExerciseLog[]};
const blank=():SetLog=>({weight:'',reps:'',leftReps:'',rightReps:''});
function dateObject(key:string){const[y,m,d]=key.split('-').map(Number);return new Date(y,m-1,d,12)}
function baseLog(date:string):WorkoutLog{const plan=planForDate(dateObject(date));return{done:false,energy:3,protein:false,water:false,limited:false,limitationNotes:'',sessionType:plan.key,exercises:(plan.exercises||[]).map(ex=>({name:ex.name,plannedSets:ex.sets,unilateral:ex.unilateral,sets:Array.from({length:ex.sets},blank)}))}}

export default function WorkoutHistoryEditor({params}:{params:{date:string}}){
  const date=params.date;const plan=useMemo(()=>planForDate(dateObject(date)),[date]);
  const[log,setLog]=useState<WorkoutLog>(()=>baseLog(date));const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[message,setMessage]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
  useEffect(()=>{fetch(`/api/workouts/today?date=${date}`).then(async r=>{if(!r.ok)throw new Error('Unable to load workout');return r.json()}).then(data=>{const next=baseLog(date);if(data.log){next.done=data.log.done;next.energy=data.log.energy;next.limited=!!data.log.limited;next.limitationNotes=data.log.limitationNotes||'';for(const row of data.log.rows){let ex=next.exercises.find(e=>e.name===row.exerciseName);if(!ex){ex={name:row.exerciseName,plannedSets:0,sets:[]};next.exercises.push(ex)}while(ex.sets.length<row.setNumber)ex.sets.push(blank());ex.sets[row.setNumber-1]={weight:row.weight||'',reps:row.reps?.toString()||'',leftReps:row.leftReps?.toString()||'',rightReps:row.rightReps?.toString()||''}}}setLog(next)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load workout')).finally(()=>setLoading(false))},[date]);
  function edit(ei:number,si:number,field:keyof SetLog,value:string){setLog(p=>{const n=structuredClone(p);n.exercises[ei].sets[si][field]=value;return n})}
  function addSet(ei:number){setLog(p=>{const n=structuredClone(p);n.exercises[ei].sets.push(blank());return n})}
  async function save(){setSaving(true);setMessage(null);setError(null);try{const r=await fetch('/api/workouts/today',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...log,date})});if(!r.ok){const j=await r.json().catch(()=>null);throw new Error(j?.error||'Unable to save workout')}setMessage('Workout updated')}catch(e){setError(e instanceof Error?e.message:'Unable to save workout')}finally{setSaving(false)}}
  async function remove(){if(!window.confirm(`Delete workout from ${date}?`))return;const r=await fetch(`/api/workouts/today?date=${date}`,{method:'DELETE'});if(!r.ok){const j=await r.json().catch(()=>null);setError(j?.error||'Unable to delete workout');return}window.location.href='/progress'}
  return <main className="shell"><header><div><p className="eyebrow">WORKOUT HISTORY</p><h1>Edit {date}</h1><p className="subtle">{plan.label} · Correct what actually happened. This does not rewrite the original plan.</p></div></header>{error&&<section className="card errorCard"><p>{error}</p></section>}{message&&<section className="card successCard"><b>{message}</b></section>}{loading?<section className="card"><p>Loading…</p></section>:<>{log.exercises.map((ex,ei)=><section className="card exercise" key={ex.name}><div className="exerciseHead"><div><h3>{ex.name}</h3></div><span>{ei+1}</span></div><div className="setHeader" style={ex.unilateral?{gridTemplateColumns:'38px 1fr 128px'}:undefined}><span>SET</span><span>WEIGHT / ASSIST</span><span>{ex.unilateral?'LEFT / RIGHT':'REPS'}</span></div>{ex.sets.map((s,si)=><div className="setRow" style={ex.unilateral?{gridTemplateColumns:'38px 1fr 128px'}:undefined} key={si}><b>{si+1}</b><input value={s.weight} onChange={e=>edit(ei,si,'weight',e.target.value)}/>{ex.unilateral?<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:5}}><input inputMode="numeric" placeholder="L" value={s.leftReps} onChange={e=>edit(ei,si,'leftReps',e.target.value)}/><input inputMode="numeric" placeholder="R" value={s.rightReps} onChange={e=>edit(ei,si,'rightReps',e.target.value)}/></div>:<input inputMode="numeric" value={s.reps} onChange={e=>edit(ei,si,'reps',e.target.value)}/>}</div>)}<button className="addSet" type="button" onClick={()=>addSet(ei)}>+ Add set</button></section>)}<section className="card"><p className="eyebrow">TRAINING CONTEXT</p><button className={`limitationToggle ${log.limited?'active':''}`} onClick={()=>setLog({...log,limited:!log.limited})}>{log.limited?'✓ Something limited this workout':'Something limited this workout'}</button>{log.limited&&<textarea value={log.limitationNotes} placeholder="What happened?" onChange={e=>setLog({...log,limitationNotes:e.target.value})}/>}<label className="subtle">Workout feel (1 could do more · 5 wrecked)<input inputMode="numeric" min="1" max="5" value={log.energy} onChange={e=>setLog({...log,energy:Number(e.target.value)||3})}/></label></section><button className="finish" disabled={saving} onClick={save}>{saving?'Saving…':'Save workout changes'}</button><button className="ghostButton dangerText" style={{width:'100%',marginTop:10}} onClick={remove}>Delete workout</button></>}<div className="inlineActions"><Link href="/progress">← Back to progress</Link></div><nav><Link href="/">Today</Link><Link href="/plan">Plan</Link></nav></main>
}
